# Ex5A NumPy Fundamentals

This notebook the basics of NumPy arrays

In [3]:
import numpy as np

## Array Basics

In [4]:
fruits = ['apple', 'banana', 'cherry', 'date']
print(fruits)

['apple', 'banana', 'cherry', 'date']


In [5]:
arr_1 = np.array(fruits)
print(arr_1)

['apple' 'banana' 'cherry' 'date']


In [6]:
print(arr_1.dtype)
#<U6 U is unicode string and 6 is the max string length in the array

<U6


In [7]:
arr_2 = np.array([
    [10,11,12],
    [13,14,15]
])
print(arr_2)

[[10 11 12]
 [13 14 15]]


In [8]:
print(arr_2.T)

[[10 13]
 [11 14]
 [12 15]]


In [11]:
print(arr_2)
#the original array was not changed, .T only returns a transposed view of the array.

[[10 11 12]
 [13 14 15]]


In [10]:
arr_3 = np.array([
    [1,3,5],
    [2,4,6]

])
print(arr_3)

[[1 3 5]
 [2 4 6]]


In [12]:
arr_4 = np.array([
    arr_3[0,2],
    arr_3[1,1]
])
print(arr_4)

[5 4]


In [13]:
arr_5 = np.ones((2, 2, 2))

print(arr_5)

[[[1. 1.]
  [1. 1.]]

 [[1. 1.]
  [1. 1.]]]
