# Exercise 1.A NumPy: Manipulating Arrays

In [1]:
import numpy as np

## Looping Through Arrays

In [2]:
arrA = np.array([[11, 12, 13], [14, 15, 16]])
print(arrA)

[[11 12 13]
 [14 15 16]]


In [5]:
for num in arrA:
  print(num * 2)

[22 24 26]
[28 30 32]


In [13]:
for num1 in arrA:
  for num2 in num1:
    print(num2 * 2)

22
24
26
28
30
32


For the first cell, it prints an entire row. The second one outputs the numbers one at a time

In [11]:
for num1 in arrA:
  for num2 in num1:
      loop_result = num1 * 2
      print(loop_result)
#The output is now repeated rows when we multiply with num1. Because num1 is staying the same throughout, so we are looping through num2 but num1 is still staying the same the whole time

[22 24 26]
[22 24 26]
[22 24 26]
[28 30 32]
[28 30 32]
[28 30 32]


## Joining and Stacking Arrays

In [14]:
joined_array_1 = np.concatenate((arrA, arrA), axis = 0)
print(joined_array_1)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [15]:
joined_array_2 = np.concatenate((arrA, arrA), axis=1)
print(joined_array_2)

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]


In [16]:
stacked_array_1 = np.stack((joined_array_1, joined_array_1))
print(stacked_array_1)

[[[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]

 [[11 12 13]
  [14 15 16]
  [11 12 13]
  [14 15 16]]]


In [31]:
#stacked_array_2 = np.stack((joined_array_1, joined_array_2))
#I have a value error here because the arrays must have the same shape, and the arrays above do not. the dimensions have to match correctly to be able to stack, one array has 3 columns and the other has 6 so they will not stack

In [32]:
another_joined_array = np.concatenate((joined_array_1, arrA))
print(another_joined_array)

[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]


In [34]:
#another_2 = np.concatenate((joined_array_1, arrA), axis=1)
#print(another_2)
#This throws a ValueError because there is not enough rows in arrA to match the rows in joined_array_1

In [37]:
a_hstack = np.hstack((arrA, arrA))
print(a_hstack)
#This adds columns but the number rows have to match

a_vstack = np.vstack((arrA, arrA))
print(a_vstack)
#This adds rows but the columnds must match

a_dstack = np.dstack((arrA, arrA))
print(a_dstack)
#This stacks along height and depth

[[11 12 13 11 12 13]
 [14 15 16 14 15 16]]
[[11 12 13]
 [14 15 16]
 [11 12 13]
 [14 15 16]]
[[[11 11]
  [12 12]
  [13 13]]

 [[14 14]
  [15 15]
  [16 16]]]


## Splitting Arrays

In [42]:
splitsky = np.split(joined_array_1, 2)
print(splitsky)
#The array was split into 2 seperate arrays. each of them are still 2d with (2,3) shape

[array([[11, 12, 13],
       [14, 15, 16]]), array([[11, 12, 13],
       [14, 15, 16]])]


In [44]:
#spliterino = np.split(joined_array_1, 3)
#print(spliterino)
#This returns a ValueError because this array cant be even split into 3. It has 4 rows so it cant be evenly split into 3 parts

## Searching and Replacing Array Values

In [45]:
result_1 = np.where(arrA % 2 == 0, arrA, 'odd')
print(result_1)

[['odd' '12' 'odd']
 ['14' 'odd' '16']]


## Sorting and Filtering Arrays

In [50]:
arrB = np.array([[7,6], [13,5], [7,3]])
arrB_sorted = np.sort(arrB)
print(arrB_sorted)

print(arrB)
z = arrB < 7
arrC = arrB[z]
print(arrC)

[[ 6  7]
 [ 5 13]
 [ 3  7]]
[[ 7  6]
 [13  5]
 [ 7  3]]
[6 5 3]


In [51]:
print(arrB)
y = arrB >= 7
arrD = arrB[y]
print(arrD)

[[ 7  6]
 [13  5]
 [ 7  3]]
[ 7 13  7]
