# Exercise 1.B NumPy Random

In [27]:
import numpy as np

## Generating Random Numbers

In [28]:
r_1 = np.random.randint(1,21, size =(2))
print(r_1)

[16 10]


In [29]:
r_2 = np.random.randint(1,21, size=(1,2))
print(r_2)

[[13  8]]


In [30]:
r_3 = np.random.rand(2,1)
print(r_3)

[[0.23557029]
 [0.43692892]]


In [31]:
r_4 = np.random.randint(20,101, size=(4,5))
print(r_4)

[[ 84  98  21  78  60]
 [ 68 100  30  70  83]
 [ 90  99  97  35  24]
 [ 80  97  42  63  30]]


In [32]:
r_5 = np.random.rand(4,5)
print(r_5)

[[0.81190951 0.67633732 0.94955732 0.77944281 0.62898686]
 [0.01288143 0.38432596 0.12280465 0.24031492 0.94602702]
 [0.8416506  0.49014846 0.13397401 0.26796125 0.49268885]
 [0.77050552 0.76898525 0.63943459 0.44947735 0.67985976]]


## Generating random Choices from an Array

In [33]:
students = np.array(['Alexander', 'Abraham', 'Max', 'Angel', 'Vanessa', 'Elizabeth', 'Gerardo', 'Blanca', 'Antonio', 'Bella', 'Jared', 'Jonathan'])
call_on = np.random.choice(students)
print(call_on)

Bella


In [34]:
breakout_groups = np.random.choice(students, size=(3,4))
print(breakout_groups)
#This would not work for real breakout room groups because we get repeated names, so it isn't realistic.

[['Bella' 'Jared' 'Gerardo' 'Antonio']
 ['Alexander' 'Antonio' 'Gerardo' 'Bella']
 ['Angel' 'Vanessa' 'Vanessa' 'Alexander']]


In [39]:
call_on_weighted = np.random.choice(
    students,
    size = 5,
    p=[ 0.3,
        0.2,
        0.1,
        0.1,
        0.05,
        0.05,
        0.05,
        0.05,
        0.03,
        0.03,
        0.04,
        0.0 ]

    )
print(call_on_weighted)
# I assigned 30% probability to index 0 and 0% probability to the last index

['Alexander' 'Alexander' 'Blanca' 'Elizabeth' 'Elizabeth']


## Generating a normal distribution

In [42]:
bell_curve = np.random.normal(loc=10, scale=5, size=(4,5))
print(bell_curve)

[[ 9.31636613  5.07802901  8.35701386  9.52747791  3.28892525]
 [ 4.96903841  4.71370398 11.65594608  6.13312425  9.53306339]
 [ 7.70621317 14.01542486 17.28822843  0.5203289  11.13720999]
 [10.05336169  4.99032516 16.64234595 14.93664048 18.79532614]]
