# Exercise 1.C Performing operations on arrays

In [ ]:
import numpy as np

## Sample Arrays

In [ ]:
r_1 = np.random.randint(1,21, size =(2))
r_2 = np.random.randint(1,21, size=(1,2))
r_3 = np.random.rand(2,1)
r_4 = np.random.randint(20,101, size=(4,5))
r_5 = np.random.rand(4,5)

## Permutations

In [ ]:
print(r_4)
print(np.random.shuffle(r_4))
#The original array shuffled after adding the function, the second line returned 'None'

[[ 51  58  70  63  67]
 [100  74  76  33  46]
 [ 31  61  95  78  65]
 [ 96  82  78  20  29]]
None


In [ ]:
new_shuffle = np.random.permutation(r_4)
print(new_shuffle)
print(r_4)
#Here, both arrays are being printed, so permutaion is not overriding the original array. We would use permuation instead of shuffle if we plan to keeo our original array

[[ 96  82  78  20  29]
 [ 31  61  95  78  65]
 [100  74  76  33  46]
 [ 51  58  70  63  67]]
[[ 96  82  78  20  29]
 [ 51  58  70  63  67]
 [ 31  61  95  78  65]
 [100  74  76  33  46]]


## Mathematical Operations

In [ ]:
print(r_1)
print(r_2)
print(r_1.shape)
print(r_2.shape)
print(np.add(r_1, r_2))
print(np.add(r_1, r_2).shape)

[20  2]
[[ 1 18]]
(2,)
(1, 2)
[[21 20]]
(1, 2)


In [ ]:
print(r_1)
print(r_3)
print(r_1.shape)
print(r_3.shape)
print(np.add(r_1, r_3))
print(np.add(r_1, r_3).shape)

[20  2]
[[0.82845346]
 [0.03735504]]
(2,)
(2, 1)
[[20.82845346  2.82845346]
 [20.03735504  2.03735504]]
(2, 2)


In [ ]:
print(r_2)
print(2_4)
print(r_2.shape)
print(r_4.shape)
#print(np.add(r_2, r_4)) Thie gave a ValueError because they could not be broadcast together with the shapes (1,2) and (4,5)
#print(np.add(r_2, r_4).shape)

[[ 1 18]]
24
(1, 2)
(4, 5)


In [ ]:
#adding = np.add(r_1, r_4)
#adding = np.add(r_2, r_4)
#adding = np.add(r_3, r_4)
#we cant add these because of the same value error as adding r_2 and r_4

In [ ]:
arr1 = np.array([1])
print(np.add(arr1, r_4))

[[ 97  83  79  21  30]
 [ 52  59  71  64  68]
 [ 32  62  96  79  66]
 [101  75  77  34  47]]


In [ ]:
arr2 = np.array([[1]])
print(np.add(arr2, r_4))

[[ 97  83  79  21  30]
 [ 52  59  71  64  68]
 [ 32  62  96  79  66]
 [101  75  77  34  47]]


In [ ]:
arr3 = np.array([1,1,1,1,1])
print(np.add(arr3, r_4))

[[ 97  83  79  21  30]
 [ 52  59  71  64  68]
 [ 32  62  96  79  66]
 [101  75  77  34  47]]


In [ ]:
arr4 = np.array([[1], [1]])
#print(np.add(arr4, r_4))
#Produces a value error because they could not be broadcast together with the shapes, (2,1) (4,5)

Broadcasting allows numpy to to perform operations on arrays with different shapes when their dimensions are compatible. they get compared from right to left. Dimensions are compatible if they're equal or if one of them is 1. The end array shape is mainly based on the bigger compatible dimensions.

## Rounding

In [ ]:
print(r_3)

[[0.82845346]
 [0.03735504]]


In [ ]:
print(np.trunc(r_3))

[[0.]
 [0.]]


In [ ]:
print(np.fix(r_3))

[[0.]
 [0.]]


In [ ]:
print(np.floor(r_3))

[[0.]
 [0.]]


In [ ]:
print(np.ceil(r_3))

[[1.]
 [1.]]


In [ ]:
print(np.round(r_3,2))

[[0.83]
 [0.04]]


## Cumulative Operations

In [ ]:
print(r_4)

[[ 96  82  78  20  29]
 [ 51  58  70  63  67]
 [ 31  61  95  78  65]
 [100  74  76  33  46]]


In [ ]:
print(np.sum([r_4]))

1273


In [ ]:
print(np.sum(r_4, axis=0))

[278 275 319 194 207]


In [ ]:
print(np.sum(r_4, axis=1))

[305 309 330 329]


In [ ]:
print(np.cumsum(r_4))

[  96  178  256  276  305  356  414  484  547  614  645  706  801  879
  944 1044 1118 1194 1227 1273]


In [ ]:
print(np.cumsum(r_4, axis=0))

[[ 96  82  78  20  29]
 [147 140 148  83  96]
 [178 201 243 161 161]
 [278 275 319 194 207]]


## Grocery Problem

In [ ]:
bag1 = np.array([2, 3, 4, 0])
bag2 = np.array([4, 0, 1, 2])
print(bag1)
print(bag2)

[2 3 4 0]
[4 0 1 2]


In [ ]:
print(f'This first bag contains {np.sum(bag1)} items, and the second bag contains {np.sum(bag2)} items')

This first bag contains 9 items, and the second bag contains 7 items


In [ ]:
total = bag1 + bag2
print(f'There are {total[0]} vegetables, {total[1]} fruits, {total[2]} boxes of snacks, and {total[3]} beverages in the two grocery bags.')

There are 6 vegetables, 3 fruits, 5 boxes of snacks, and 2 beverages in the two grocery bags.


## Teamwork

In [ ]:
Ali = np.array([5, 4, 6, 4, 2])

In [ ]:
Ben = np.array([0, 5, 5, 3, 4])

In [ ]:
Carla = np.array([3, 6, 0, 3, 4])

In [ ]:
all_knocks = Ali + Ben + Carla
print(all_knocks)

[ 8 15 11 10 10]


In [ ]:
ali_week = np.sum(Ali)
print(ali_week)

21


In [ ]:
ben_week = np.sum(Ben)
print(ben_week)

17


In [ ]:
carla_week = np.sum(Carla)
print(carla_week)

16


In [ ]:
group_week = np.sum(all_knocks)
print(group_week)

54


In [ ]:
rolling_total = np.cumsum(all_knocks)
print(rolling_total)

[ 8 23 34 44 54]


In [ ]:
estimated_votes = rolling_total / 2
print(estimated_votes)

[ 4.  11.5 17.  22.  27. ]
